version: 2

updates:
  # note, we do not update examples/playwright as this is a specific test for
  # an exact version of playwright

  - package-ecosystem: "npm"
    directory: "./"
    open-pull-requests-limit: 2
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "Pacific/Auckland"

  - package-ecosystem: "npm"
    directory: "test-packages/playwright-v1"
    open-pull-requests-limit: 2
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "Pacific/Auckland"
