version: 2

updates:

  - package-ecosystem: "npm"
    directory: "./packages/shotbro"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: monthly

  - package-ecosystem: "npm"
    directory: "./packages/shotbro-playwright"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: monthly

  - package-ecosystem: "npm"
    directory: "examples/playwright-v1"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: monthly

  - package-ecosystem: "npm"
    directory: "examples/duckduckgo-simple"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: monthly
