name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Test
        run: npm run test:ci

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 2
          name: playwright-tests-compare-to
          path: |
            packages/**/__snapshots__/compare
