name: CI

on:
  push:
    branches-ignore: [ main ]
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache-dependency-path: |
            client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run build

      - name: Test
        working-directory: client
        run: npm run test

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 2
          name: playwright-tests-compare-to
          path: |
            client/**/__snapshots__/compare


#  examples:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        # note, node 14 was giving trouble Sep 2022, drop support for now
#        node: [ 16, 18 ]
#    name: Node ${{ matrix.node }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Setup node
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node }}
#
#      - name: Install dependencies
#        working-directory: examples/playwright-v1
#        run: npm ci
#
#      - name: Test
#        working-directory: examples/playwright-v1
#        run: npm run test
