name: ShotBro Playwright Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/shotbro-playwright/**'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: |
            packages/shotbro-playwright/package-lock.json

      - name: Install dependencies
        working-directory: packages/shotbro-playwright
        run: npm ci

      - name: Build
        working-directory: packages/shotbro-playwright
        run: npm run build

      - name: Test
        working-directory: packages/shotbro-playwright
        run: npm run test

      - uses: google-github-actions/release-please-action@v3
        id: release
        name: Release
        with:
          monorepo-tags: true
          path: packages/shotbro-playwright
          changelog-path: CHANGELOG.md
          release-type: node
          package-name: 'shotbro-playwright'

      - if: ${{ steps.release.outputs.releases_created }}
        name: Publish
        working-directory: packages/shotbro-playwright
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
