name: ShotBro Core Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: |
            packages/shotbro/package-lock.json

      - name: Install dependencies
        working-directory: packages/shotbro
        run: npm ci

      - name: Build
        working-directory: packages/shotbro
        run: npm run build

      - name: Test
        working-directory: packages/shotbro
        run: npm run test

      - uses: google-github-actions/release-please-action@v3
        id: release
        name: Release
        with:
          monorepo-tags: true
          path: packages/shotbro
          changelog-path: CHANGELOG.md
          release-type: node
          package-name: 'shotbro'

      - if: ${{ steps.release.outputs.releases_created }}
        name: Publish
        working-directory: packages/shotbro
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
