name: ShotBro Core Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/shotbro/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: packages/shotbro
        run: npm ci

      - name: Build
        working-directory: packages/shotbro
        run: npm run build

      - name: Test
        working-directory: packages/shotbro
        run: npm run test

      - uses: google-github-actions/release-please-action@v4
        id: release
        name: Release
        with:
          path: packages/shotbro

      - if: ${{ steps.release.outputs.releases_created }}
        name: Publish
        working-directory: packages/shotbro
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
