name: ShotBro Playwright Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/shotbro-playwright/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        working-directory: packages/shotbro-playwright
        run: npm ci

      - name: Build
        working-directory: packages/shotbro-playwright
        run: npm run build

      - name: Test
        working-directory: packages/shotbro-playwright
        run: npm run test

      - uses: googleapis/release-please-action@v4
        id: release
        name: Release
        with:
          path: packages/shotbro-playwright
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - if: ${{ steps.release.outputs.releases_created }}
        name: Publish
        working-directory: packages/shotbro-playwright
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
